### ISSUE TITLE
Word level audio start and end

### ISSUE THREAD

**Issue by padmalcom** [jonatasgrosman/asrecognition#32]
Hi @jonatasgrosman, first of all: Thank you for your great library. Can you imagine a way to implement a function that prints single recognized words with each individual start and end time in e.g. milliseconds?

**Comment by jonatasgrosman** [comment]
Hi @padmalcom ! I've already implemented that in a new tool https://github.com/jonatasgrosman/huggingsound :)

**Comment by padmalcom** [comment]
Awesome :) Thank you!
