### ISSUE TITLE
Setting device for ASR model

### ISSUE THREAD

**Issue by MorenoLaQuatra** [jonatasgrosman/asrecognition#5]
Hi Jonatas,

First of all thank you for the amazing work, both for pre-trained language-specific models and for the very easy-to-use library.

I want to ask if is possible to specify the device (GPU or CPU) for the ASR model. Actually, I tried:

`device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')`

However, it doesn't seem to work. Any suggestion?

**Comment by jonatasgrosman** [comment]
Try this...

`asr = ASREngine("en", device="cuda")`
